### ISSUE TITLE
Could not set time

### ISSUE THREAD

**Issue by hadif66** [nopnop2002/esp-idf-ds1307#5]
I am using a ds1307 module with ESP32 microcontroller, in the menu config I set gpios as SDA = 21 , SCL =22 but when I compile and run the project it gives me this error: I2CDEV: Could not write to device [0x68 at 0]: 263

**Comment by ConorMcGregor87** [comment]
Sorry, but i have this problem to. 21 SCL 22 SDA. ESP32-WROOM-32U.
E (1575) I2CDEV: Could not read from device [0x68 at 0]: 263
